{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 208,
   "id": "7a16ee94",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import pickle\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 209,
   "id": "6747c1b1",
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pickle.load(open('dataset_level2.pkl','rb'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 210,
   "id": "a7c5f73a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>match_id</th>\n",
       "      <th>batting_team</th>\n",
       "      <th>balling_team</th>\n",
       "      <th>ball</th>\n",
       "      <th>runs</th>\n",
       "      <th>player_dismissed</th>\n",
       "      <th>city</th>\n",
       "      <th>venue</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Melbourne Cricket Ground</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.2</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Melbourne Cricket Ground</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.3</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Melbourne Cricket Ground</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.4</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Melbourne Cricket Ground</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.5</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Melbourne Cricket Ground</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>121</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.3</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>R Premadasa Stadium</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>122</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.4</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>R Premadasa Stadium</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>123</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.5</td>\n",
       "      <td>0</td>\n",
       "      <td>DM de Silva</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>R Premadasa Stadium</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>124</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.6</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>R Premadasa Stadium</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>125</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.7</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>R Premadasa Stadium</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>63888 rows × 8 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     match_id batting_team balling_team  ball  runs player_dismissed     city  \\\n",
       "0           2    Australia    Sri Lanka   0.1     0                0      NaN   \n",
       "1           2    Australia    Sri Lanka   0.2     0                0      NaN   \n",
       "2           2    Australia    Sri Lanka   0.3     1                0      NaN   \n",
       "3           2    Australia    Sri Lanka   0.4     2                0      NaN   \n",
       "4           2    Australia    Sri Lanka   0.5     0                0      NaN   \n",
       "..        ...          ...          ...   ...   ...              ...      ...   \n",
       "121       964    Sri Lanka    Australia  19.3     1                0  Colombo   \n",
       "122       964    Sri Lanka    Australia  19.4     0                0  Colombo   \n",
       "123       964    Sri Lanka    Australia  19.5     0      DM de Silva  Colombo   \n",
       "124       964    Sri Lanka    Australia  19.6     2                0  Colombo   \n",
       "125       964    Sri Lanka    Australia  19.7     1                0  Colombo   \n",
       "\n",
       "                        venue  \n",
       "0    Melbourne Cricket Ground  \n",
       "1    Melbourne Cricket Ground  \n",
       "2    Melbourne Cricket Ground  \n",
       "3    Melbourne Cricket Ground  \n",
       "4    Melbourne Cricket Ground  \n",
       "..                        ...  \n",
       "121       R Premadasa Stadium  \n",
       "122       R Premadasa Stadium  \n",
       "123       R Premadasa Stadium  \n",
       "124       R Premadasa Stadium  \n",
       "125       R Premadasa Stadium  \n",
       "\n",
       "[63888 rows x 8 columns]"
      ]
     },
     "execution_count": 210,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df\n",
    "# batting_team\n",
    "# bowling team\n",
    "# city\n",
    "# current score\n",
    "# ball left\n",
    "# wickets left\n",
    "# current rr\n",
    "# last five"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 211,
   "id": "104ac5af",
   "metadata": {},
   "outputs": [],
   "source": [
    "cities=np.where(df[\"city\"].isnull(),df[\"venue\"].str.split().apply(lambda x:x[0]),df[\"city\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 212,
   "id": "785022e1",
   "metadata": {},
   "outputs": [],
   "source": [
    "df[\"city\"]=cities"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 213,
   "id": "ecd5f4af",
   "metadata": {},
   "outputs": [],
   "source": [
    "df.drop(columns=[\"venue\"],inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 214,
   "id": "693b86d1",
   "metadata": {},
   "outputs": [],
   "source": [
    "df[\"player_dismissed\"]=df[\"player_dismissed\"].apply(lambda x:0 if x=='0' else 1)\n",
    "df[\"player_dismissed\"]=df[\"player_dismissed\"].astype(\"int\")\n",
    "df[\"player_dismissed\"]=df.groupby(\"match_id\").cumsum()[\"player_dismissed\"] \n",
    "df[\"wickets_left\"]=10-df[\"player_dismissed\"]\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 215,
   "id": "9f3a2779",
   "metadata": {},
   "outputs": [],
   "source": [
    "df.drop(columns=[\"player_dismissed\"],inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 216,
   "id": "227b8f57",
   "metadata": {},
   "outputs": [],
   "source": [
    "eligible_cities = df['city'].value_counts()[df['city'].value_counts() > 600].index.tolist()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 217,
   "id": "0aadc58a",
   "metadata": {},
   "outputs": [],
   "source": [
    "df = df[df['city'].isin(eligible_cities)]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 218,
   "id": "8d99242c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>match_id</th>\n",
       "      <th>batting_team</th>\n",
       "      <th>balling_team</th>\n",
       "      <th>ball</th>\n",
       "      <th>runs</th>\n",
       "      <th>city</th>\n",
       "      <th>wickets_left</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.1</td>\n",
       "      <td>0</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.2</td>\n",
       "      <td>0</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.3</td>\n",
       "      <td>1</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.4</td>\n",
       "      <td>2</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.5</td>\n",
       "      <td>0</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>121</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.3</td>\n",
       "      <td>1</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>122</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.4</td>\n",
       "      <td>0</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>123</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.5</td>\n",
       "      <td>0</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>124</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.6</td>\n",
       "      <td>2</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>125</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.7</td>\n",
       "      <td>1</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>50501 rows × 7 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     match_id batting_team balling_team  ball  runs       city  wickets_left\n",
       "0           2    Australia    Sri Lanka   0.1     0  Melbourne            10\n",
       "1           2    Australia    Sri Lanka   0.2     0  Melbourne            10\n",
       "2           2    Australia    Sri Lanka   0.3     1  Melbourne            10\n",
       "3           2    Australia    Sri Lanka   0.4     2  Melbourne            10\n",
       "4           2    Australia    Sri Lanka   0.5     0  Melbourne            10\n",
       "..        ...          ...          ...   ...   ...        ...           ...\n",
       "121       964    Sri Lanka    Australia  19.3     1    Colombo             2\n",
       "122       964    Sri Lanka    Australia  19.4     0    Colombo             2\n",
       "123       964    Sri Lanka    Australia  19.5     0    Colombo             1\n",
       "124       964    Sri Lanka    Australia  19.6     2    Colombo             1\n",
       "125       964    Sri Lanka    Australia  19.7     1    Colombo             1\n",
       "\n",
       "[50501 rows x 7 columns]"
      ]
     },
     "execution_count": 218,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 219,
   "id": "c13286ae",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-219-bfd4650497fe>:1: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[\"current_score\"]=df.groupby(\"match_id\").cumsum()[\"runs\"]\n"
     ]
    }
   ],
   "source": [
    "df[\"current_score\"]=df.groupby(\"match_id\").cumsum()[\"runs\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 220,
   "id": "442fa4dd",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>match_id</th>\n",
       "      <th>batting_team</th>\n",
       "      <th>balling_team</th>\n",
       "      <th>ball</th>\n",
       "      <th>runs</th>\n",
       "      <th>city</th>\n",
       "      <th>wickets_left</th>\n",
       "      <th>current_score</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.1</td>\n",
       "      <td>0</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.2</td>\n",
       "      <td>0</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.3</td>\n",
       "      <td>1</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.4</td>\n",
       "      <td>2</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.5</td>\n",
       "      <td>0</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>121</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.3</td>\n",
       "      <td>1</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>2</td>\n",
       "      <td>125</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>122</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.4</td>\n",
       "      <td>0</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>2</td>\n",
       "      <td>125</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>123</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.5</td>\n",
       "      <td>0</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>1</td>\n",
       "      <td>125</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>124</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.6</td>\n",
       "      <td>2</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>1</td>\n",
       "      <td>127</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>125</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.7</td>\n",
       "      <td>1</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>1</td>\n",
       "      <td>128</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>50501 rows × 8 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     match_id batting_team balling_team  ball  runs       city  wickets_left  \\\n",
       "0           2    Australia    Sri Lanka   0.1     0  Melbourne            10   \n",
       "1           2    Australia    Sri Lanka   0.2     0  Melbourne            10   \n",
       "2           2    Australia    Sri Lanka   0.3     1  Melbourne            10   \n",
       "3           2    Australia    Sri Lanka   0.4     2  Melbourne            10   \n",
       "4           2    Australia    Sri Lanka   0.5     0  Melbourne            10   \n",
       "..        ...          ...          ...   ...   ...        ...           ...   \n",
       "121       964    Sri Lanka    Australia  19.3     1    Colombo             2   \n",
       "122       964    Sri Lanka    Australia  19.4     0    Colombo             2   \n",
       "123       964    Sri Lanka    Australia  19.5     0    Colombo             1   \n",
       "124       964    Sri Lanka    Australia  19.6     2    Colombo             1   \n",
       "125       964    Sri Lanka    Australia  19.7     1    Colombo             1   \n",
       "\n",
       "     current_score  \n",
       "0                0  \n",
       "1                0  \n",
       "2                1  \n",
       "3                3  \n",
       "4                3  \n",
       "..             ...  \n",
       "121            125  \n",
       "122            125  \n",
       "123            125  \n",
       "124            127  \n",
       "125            128  \n",
       "\n",
       "[50501 rows x 8 columns]"
      ]
     },
     "execution_count": 220,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 221,
   "id": "445aacf8",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-221-4fd5a57c1fcd>:1: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['over'] = df['ball'].apply(lambda x:str(x).split(\".\")[0])\n",
      "<ipython-input-221-4fd5a57c1fcd>:2: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['ball_no'] = df['ball'].apply(lambda x:str(x).split(\".\")[1])\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>match_id</th>\n",
       "      <th>batting_team</th>\n",
       "      <th>balling_team</th>\n",
       "      <th>ball</th>\n",
       "      <th>runs</th>\n",
       "      <th>city</th>\n",
       "      <th>wickets_left</th>\n",
       "      <th>current_score</th>\n",
       "      <th>over</th>\n",
       "      <th>ball_no</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.1</td>\n",
       "      <td>0</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.2</td>\n",
       "      <td>0</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.3</td>\n",
       "      <td>1</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.4</td>\n",
       "      <td>2</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.5</td>\n",
       "      <td>0</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>121</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.3</td>\n",
       "      <td>1</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>2</td>\n",
       "      <td>125</td>\n",
       "      <td>19</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>122</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.4</td>\n",
       "      <td>0</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>2</td>\n",
       "      <td>125</td>\n",
       "      <td>19</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>123</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.5</td>\n",
       "      <td>0</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>1</td>\n",
       "      <td>125</td>\n",
       "      <td>19</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>124</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.6</td>\n",
       "      <td>2</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>1</td>\n",
       "      <td>127</td>\n",
       "      <td>19</td>\n",
       "      <td>6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>125</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.7</td>\n",
       "      <td>1</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>1</td>\n",
       "      <td>128</td>\n",
       "      <td>19</td>\n",
       "      <td>7</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>50501 rows × 10 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     match_id batting_team balling_team  ball  runs       city  wickets_left  \\\n",
       "0           2    Australia    Sri Lanka   0.1     0  Melbourne            10   \n",
       "1           2    Australia    Sri Lanka   0.2     0  Melbourne            10   \n",
       "2           2    Australia    Sri Lanka   0.3     1  Melbourne            10   \n",
       "3           2    Australia    Sri Lanka   0.4     2  Melbourne            10   \n",
       "4           2    Australia    Sri Lanka   0.5     0  Melbourne            10   \n",
       "..        ...          ...          ...   ...   ...        ...           ...   \n",
       "121       964    Sri Lanka    Australia  19.3     1    Colombo             2   \n",
       "122       964    Sri Lanka    Australia  19.4     0    Colombo             2   \n",
       "123       964    Sri Lanka    Australia  19.5     0    Colombo             1   \n",
       "124       964    Sri Lanka    Australia  19.6     2    Colombo             1   \n",
       "125       964    Sri Lanka    Australia  19.7     1    Colombo             1   \n",
       "\n",
       "     current_score over ball_no  \n",
       "0                0    0       1  \n",
       "1                0    0       2  \n",
       "2                1    0       3  \n",
       "3                3    0       4  \n",
       "4                3    0       5  \n",
       "..             ...  ...     ...  \n",
       "121            125   19       3  \n",
       "122            125   19       4  \n",
       "123            125   19       5  \n",
       "124            127   19       6  \n",
       "125            128   19       7  \n",
       "\n",
       "[50501 rows x 10 columns]"
      ]
     },
     "execution_count": 221,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df['over'] = df['ball'].apply(lambda x:str(x).split(\".\")[0])\n",
    "df['ball_no'] = df['ball'].apply(lambda x:str(x).split(\".\")[1])\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 222,
   "id": "778e1027",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-222-e7d17f656852>:1: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['balls_bowled'] = (df['over'].astype('int')*6) + df['ball_no'].astype('int')\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>match_id</th>\n",
       "      <th>batting_team</th>\n",
       "      <th>balling_team</th>\n",
       "      <th>ball</th>\n",
       "      <th>runs</th>\n",
       "      <th>city</th>\n",
       "      <th>wickets_left</th>\n",
       "      <th>current_score</th>\n",
       "      <th>over</th>\n",
       "      <th>ball_no</th>\n",
       "      <th>balls_bowled</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.1</td>\n",
       "      <td>0</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.2</td>\n",
       "      <td>0</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.3</td>\n",
       "      <td>1</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.4</td>\n",
       "      <td>2</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.5</td>\n",
       "      <td>0</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>121</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.3</td>\n",
       "      <td>1</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>2</td>\n",
       "      <td>125</td>\n",
       "      <td>19</td>\n",
       "      <td>3</td>\n",
       "      <td>117</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>122</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.4</td>\n",
       "      <td>0</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>2</td>\n",
       "      <td>125</td>\n",
       "      <td>19</td>\n",
       "      <td>4</td>\n",
       "      <td>118</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>123</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.5</td>\n",
       "      <td>0</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>1</td>\n",
       "      <td>125</td>\n",
       "      <td>19</td>\n",
       "      <td>5</td>\n",
       "      <td>119</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>124</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.6</td>\n",
       "      <td>2</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>1</td>\n",
       "      <td>127</td>\n",
       "      <td>19</td>\n",
       "      <td>6</td>\n",
       "      <td>120</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>125</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.7</td>\n",
       "      <td>1</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>1</td>\n",
       "      <td>128</td>\n",
       "      <td>19</td>\n",
       "      <td>7</td>\n",
       "      <td>121</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>50501 rows × 11 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     match_id batting_team balling_team  ball  runs       city  wickets_left  \\\n",
       "0           2    Australia    Sri Lanka   0.1     0  Melbourne            10   \n",
       "1           2    Australia    Sri Lanka   0.2     0  Melbourne            10   \n",
       "2           2    Australia    Sri Lanka   0.3     1  Melbourne            10   \n",
       "3           2    Australia    Sri Lanka   0.4     2  Melbourne            10   \n",
       "4           2    Australia    Sri Lanka   0.5     0  Melbourne            10   \n",
       "..        ...          ...          ...   ...   ...        ...           ...   \n",
       "121       964    Sri Lanka    Australia  19.3     1    Colombo             2   \n",
       "122       964    Sri Lanka    Australia  19.4     0    Colombo             2   \n",
       "123       964    Sri Lanka    Australia  19.5     0    Colombo             1   \n",
       "124       964    Sri Lanka    Australia  19.6     2    Colombo             1   \n",
       "125       964    Sri Lanka    Australia  19.7     1    Colombo             1   \n",
       "\n",
       "     current_score over ball_no  balls_bowled  \n",
       "0                0    0       1             1  \n",
       "1                0    0       2             2  \n",
       "2                1    0       3             3  \n",
       "3                3    0       4             4  \n",
       "4                3    0       5             5  \n",
       "..             ...  ...     ...           ...  \n",
       "121            125   19       3           117  \n",
       "122            125   19       4           118  \n",
       "123            125   19       5           119  \n",
       "124            127   19       6           120  \n",
       "125            128   19       7           121  \n",
       "\n",
       "[50501 rows x 11 columns]"
      ]
     },
     "execution_count": 222,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df['balls_bowled'] = (df['over'].astype('int')*6) + df['ball_no'].astype('int')\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 223,
   "id": "b8f9be12",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-223-7ed065e8960c>:1: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['balls_left'] = 120 - df['balls_bowled']\n",
      "<ipython-input-223-7ed065e8960c>:2: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['balls_left'] = df['balls_left'].apply(lambda x:0 if x<0 else x)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>match_id</th>\n",
       "      <th>batting_team</th>\n",
       "      <th>balling_team</th>\n",
       "      <th>ball</th>\n",
       "      <th>runs</th>\n",
       "      <th>city</th>\n",
       "      <th>wickets_left</th>\n",
       "      <th>current_score</th>\n",
       "      <th>over</th>\n",
       "      <th>ball_no</th>\n",
       "      <th>balls_bowled</th>\n",
       "      <th>balls_left</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.1</td>\n",
       "      <td>0</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>119</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.2</td>\n",
       "      <td>0</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>118</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.3</td>\n",
       "      <td>1</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>3</td>\n",
       "      <td>117</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.4</td>\n",
       "      <td>2</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>116</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>0.5</td>\n",
       "      <td>0</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>10</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>115</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>121</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.3</td>\n",
       "      <td>1</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>2</td>\n",
       "      <td>125</td>\n",
       "      <td>19</td>\n",
       "      <td>3</td>\n",
       "      <td>117</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>122</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.4</td>\n",
       "      <td>0</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>2</td>\n",
       "      <td>125</td>\n",
       "      <td>19</td>\n",
       "      <td>4</td>\n",
       "      <td>118</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>123</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.5</td>\n",
       "      <td>0</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>1</td>\n",
       "      <td>125</td>\n",
       "      <td>19</td>\n",
       "      <td>5</td>\n",
       "      <td>119</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>124</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.6</td>\n",
       "      <td>2</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>1</td>\n",
       "      <td>127</td>\n",
       "      <td>19</td>\n",
       "      <td>6</td>\n",
       "      <td>120</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>125</th>\n",
       "      <td>964</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.7</td>\n",
       "      <td>1</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>1</td>\n",
       "      <td>128</td>\n",
       "      <td>19</td>\n",
       "      <td>7</td>\n",
       "      <td>121</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>50501 rows × 12 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     match_id batting_team balling_team  ball  runs       city  wickets_left  \\\n",
       "0           2    Australia    Sri Lanka   0.1     0  Melbourne            10   \n",
       "1           2    Australia    Sri Lanka   0.2     0  Melbourne            10   \n",
       "2           2    Australia    Sri Lanka   0.3     1  Melbourne            10   \n",
       "3           2    Australia    Sri Lanka   0.4     2  Melbourne            10   \n",
       "4           2    Australia    Sri Lanka   0.5     0  Melbourne            10   \n",
       "..        ...          ...          ...   ...   ...        ...           ...   \n",
       "121       964    Sri Lanka    Australia  19.3     1    Colombo             2   \n",
       "122       964    Sri Lanka    Australia  19.4     0    Colombo             2   \n",
       "123       964    Sri Lanka    Australia  19.5     0    Colombo             1   \n",
       "124       964    Sri Lanka    Australia  19.6     2    Colombo             1   \n",
       "125       964    Sri Lanka    Australia  19.7     1    Colombo             1   \n",
       "\n",
       "     current_score over ball_no  balls_bowled  balls_left  \n",
       "0                0    0       1             1         119  \n",
       "1                0    0       2             2         118  \n",
       "2                1    0       3             3         117  \n",
       "3                3    0       4             4         116  \n",
       "4                3    0       5             5         115  \n",
       "..             ...  ...     ...           ...         ...  \n",
       "121            125   19       3           117           3  \n",
       "122            125   19       4           118           2  \n",
       "123            125   19       5           119           1  \n",
       "124            127   19       6           120           0  \n",
       "125            128   19       7           121           0  \n",
       "\n",
       "[50501 rows x 12 columns]"
      ]
     },
     "execution_count": 223,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df['balls_left'] = 120 - df['balls_bowled']\n",
    "df['balls_left'] = df['balls_left'].apply(lambda x:0 if x<0 else x)\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 224,
   "id": "39e21ec4",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-224-fad47fc85776>:1: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['crr'] = (df['current_score']*6)/df['balls_bowled']\n"
     ]
    }
   ],
   "source": [
    "df['crr'] = (df['current_score']*6)/df['balls_bowled']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 225,
   "id": "03c20ad5",
   "metadata": {},
   "outputs": [],
   "source": [
    "groups = df.groupby('match_id')\n",
    "\n",
    "match_ids = df['match_id'].unique()\n",
    "last_five = []\n",
    "for id in match_ids:\n",
    "    last_five.extend(groups.get_group(id).rolling(window=30).sum()['runs'].values.tolist())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 226,
   "id": "bdac40a1",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-226-83d24d575aa4>:1: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['last_five'] = last_five\n"
     ]
    }
   ],
   "source": [
    "df['last_five'] = last_five"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 227,
   "id": "525f8c2b",
   "metadata": {},
   "outputs": [],
   "source": [
    "final_df = df.groupby('match_id').sum()['runs'].reset_index().merge(df,on='match_id')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 228,
   "id": "5e632e4f",
   "metadata": {},
   "outputs": [],
   "source": [
    "final_df=final_df[['batting_team','balling_team','city','current_score','balls_left','wickets_left','crr','last_five','runs_x']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 229,
   "id": "4cb4ea9e",
   "metadata": {},
   "outputs": [],
   "source": [
    "final_df.dropna(inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 230,
   "id": "e94997fd",
   "metadata": {},
   "outputs": [],
   "source": [
    "final_df = final_df.sample(final_df.shape[0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 231,
   "id": "bb769906",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>batting_team</th>\n",
       "      <th>balling_team</th>\n",
       "      <th>city</th>\n",
       "      <th>current_score</th>\n",
       "      <th>balls_left</th>\n",
       "      <th>wickets_left</th>\n",
       "      <th>crr</th>\n",
       "      <th>last_five</th>\n",
       "      <th>runs_x</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>13212</th>\n",
       "      <td>Australia</td>\n",
       "      <td>India</td>\n",
       "      <td>Sydney</td>\n",
       "      <td>47</td>\n",
       "      <td>86</td>\n",
       "      <td>9</td>\n",
       "      <td>8.294118</td>\n",
       "      <td>38.0</td>\n",
       "      <td>186</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13450</th>\n",
       "      <td>New Zealand</td>\n",
       "      <td>West Indies</td>\n",
       "      <td>Mount Maunganui</td>\n",
       "      <td>49</td>\n",
       "      <td>84</td>\n",
       "      <td>9</td>\n",
       "      <td>8.166667</td>\n",
       "      <td>44.0</td>\n",
       "      <td>238</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>39427</th>\n",
       "      <td>Pakistan</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Mirpur</td>\n",
       "      <td>179</td>\n",
       "      <td>8</td>\n",
       "      <td>6</td>\n",
       "      <td>9.589286</td>\n",
       "      <td>49.0</td>\n",
       "      <td>191</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>45741</th>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>New Zealand</td>\n",
       "      <td>Auckland</td>\n",
       "      <td>64</td>\n",
       "      <td>59</td>\n",
       "      <td>6</td>\n",
       "      <td>6.295082</td>\n",
       "      <td>32.0</td>\n",
       "      <td>142</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27618</th>\n",
       "      <td>Australia</td>\n",
       "      <td>England</td>\n",
       "      <td>Adelaide</td>\n",
       "      <td>96</td>\n",
       "      <td>47</td>\n",
       "      <td>8</td>\n",
       "      <td>7.890411</td>\n",
       "      <td>40.0</td>\n",
       "      <td>157</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>43533</th>\n",
       "      <td>South Africa</td>\n",
       "      <td>Bangladesh</td>\n",
       "      <td>Mirpur</td>\n",
       "      <td>89</td>\n",
       "      <td>42</td>\n",
       "      <td>7</td>\n",
       "      <td>6.846154</td>\n",
       "      <td>36.0</td>\n",
       "      <td>148</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26609</th>\n",
       "      <td>New Zealand</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Christchurch</td>\n",
       "      <td>72</td>\n",
       "      <td>63</td>\n",
       "      <td>7</td>\n",
       "      <td>7.578947</td>\n",
       "      <td>28.0</td>\n",
       "      <td>214</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26482</th>\n",
       "      <td>New Zealand</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Wellington</td>\n",
       "      <td>41</td>\n",
       "      <td>68</td>\n",
       "      <td>7</td>\n",
       "      <td>4.730769</td>\n",
       "      <td>32.0</td>\n",
       "      <td>118</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>47691</th>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>West Indies</td>\n",
       "      <td>Bangalore</td>\n",
       "      <td>92</td>\n",
       "      <td>20</td>\n",
       "      <td>4</td>\n",
       "      <td>5.520000</td>\n",
       "      <td>28.0</td>\n",
       "      <td>122</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33802</th>\n",
       "      <td>West Indies</td>\n",
       "      <td>Australia</td>\n",
       "      <td>Colombo</td>\n",
       "      <td>133</td>\n",
       "      <td>29</td>\n",
       "      <td>8</td>\n",
       "      <td>8.769231</td>\n",
       "      <td>57.0</td>\n",
       "      <td>205</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>38477 rows × 9 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "       batting_team balling_team             city  current_score  balls_left  \\\n",
       "13212     Australia        India           Sydney             47          86   \n",
       "13450   New Zealand  West Indies  Mount Maunganui             49          84   \n",
       "39427      Pakistan    Australia           Mirpur            179           8   \n",
       "45741     Sri Lanka  New Zealand         Auckland             64          59   \n",
       "27618     Australia      England         Adelaide             96          47   \n",
       "...             ...          ...              ...            ...         ...   \n",
       "43533  South Africa   Bangladesh           Mirpur             89          42   \n",
       "26609   New Zealand    Australia     Christchurch             72          63   \n",
       "26482   New Zealand    Australia       Wellington             41          68   \n",
       "47691     Sri Lanka  West Indies        Bangalore             92          20   \n",
       "33802   West Indies    Australia          Colombo            133          29   \n",
       "\n",
       "       wickets_left       crr  last_five  runs_x  \n",
       "13212             9  8.294118       38.0     186  \n",
       "13450             9  8.166667       44.0     238  \n",
       "39427             6  9.589286       49.0     191  \n",
       "45741             6  6.295082       32.0     142  \n",
       "27618             8  7.890411       40.0     157  \n",
       "...             ...       ...        ...     ...  \n",
       "43533             7  6.846154       36.0     148  \n",
       "26609             7  7.578947       28.0     214  \n",
       "26482             7  4.730769       32.0     118  \n",
       "47691             4  5.520000       28.0     122  \n",
       "33802             8  8.769231       57.0     205  \n",
       "\n",
       "[38477 rows x 9 columns]"
      ]
     },
     "execution_count": 231,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "final_df"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "aac0a540",
   "metadata": {},
   "source": [
    "# Machine learning Algo:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 232,
   "id": "e268f2c7",
   "metadata": {},
   "outputs": [],
   "source": [
    "x=final_df.drop(columns=[\"runs_x\"])\n",
    "y=final_df[\"runs_x\"]\n",
    "from sklearn.model_selection import train_test_split\n",
    "x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.3,random_state=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 233,
   "id": "13b4be1b",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.compose import ColumnTransformer\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.preprocessing import OneHotEncoder\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.ensemble import RandomForestRegressor\n",
    "\n",
    "from sklearn.metrics import r2_score,mean_absolute_error"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 234,
   "id": "c3a1d672",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: xgboost in c:\\users\\sharm\\anaconda3\\lib\\site-packages (1.5.2)\n",
      "Requirement already satisfied: scipy in c:\\users\\sharm\\anaconda3\\lib\\site-packages (from xgboost) (1.6.2)\n",
      "Requirement already satisfied: numpy in c:\\users\\sharm\\anaconda3\\lib\\site-packages (from xgboost) (1.20.1)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install xgboost"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 235,
   "id": "eb86d4b4",
   "metadata": {},
   "outputs": [],
   "source": [
    "from xgboost import XGBRegressor"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 236,
   "id": "b5e1c14c",
   "metadata": {},
   "outputs": [],
   "source": [
    "trf = ColumnTransformer([\n",
    "    ('trf',OneHotEncoder(sparse=False,drop='first'),['batting_team','balling_team','city'])\n",
    "]\n",
    ",remainder='passthrough')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 237,
   "id": "b48f5e8b",
   "metadata": {},
   "outputs": [],
   "source": [
    "pipe = Pipeline(steps=[\n",
    "    ('step1',trf),\n",
    "    ('step2',StandardScaler()),\n",
    "    ('step3',XGBRegressor(n_estimators=1000,learning_rate=0.2,max_depth=12,random_state=1))\n",
    "])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 238,
   "id": "1806c353",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.9865895391430857\n",
      "1.753681675229565\n"
     ]
    }
   ],
   "source": [
    "pipe.fit(x_train,y_train)\n",
    "y_pred = pipe.predict(x_test)\n",
    "print(r2_score(y_test,y_pred))\n",
    "print(mean_absolute_error(y_test,y_pred))\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d91ac9f9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
